@baseUrl = http://localhost:3000/v0/brand


### GET /{id}
GET {{baseUrl}}/2 HTTP/1.1
content-type: application/json

### Create
POST {{baseUrl}}/ HTTP/1.1
content-type: application/json

{    
    "name": "Ekko",
    "created_by": "admin",
    "updated_by": "admin"
}

### UPDATE
# Specify ID via path and only POST updated fields
POST {{baseUrl}}/2 HTTP/1.1
content-type: application/json

{    
    "name": "Ekko",
    "created_by": "admin",
    "updated_by": "admin"
}
