@baseUrl = http://localhost:3000/v0/item


### GET /id.{id}
GET {{baseUrl}}/id.41/ HTTP/1.1
content-type: application/json

### GET /{sku_code}
GET {{baseUrl}}/8025727438204 HTTP/1.1
content-type: application/json

### CREATE
POST {{baseUrl}}/ HTTP/1.1
content-type: application/json

{
    "code": "ecko-unltd-giay-sneakers-nam-is22-26511",
    "name": "Ecko Unltd giày sneakers nam IS22-26511",
    "variant_attributes": {
      "color": "red",
      "size": "L"
    },
    "master_sku": "",
    "primary_category_id": 4,
    "brand_id": 3,
    "categories_id": [18, 22],
    "created_by": "admin",
    "updated_by": "admin"
}

### UPDATE 
# Specify ID via path and only POST updated fields
POST {{baseUrl}}/id.41 HTTP/1.1
content-type: application/json

{ 
    "variant_attributes": {
      "color": "red",
      "size": "L"
    },    
    "updated_by": "admin"
}

### SEARCH
POST {{baseUrl}}/search HTTP/1.1
content-type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "store_code": [
              "3101"
            ]
          }
        }
      ],
      "must_not": [],
      "should": []
    }
  },
  "from": 0,
  "size": 1,
  "aggs": {
    "facetStatus": {
      "terms": {
        "field": "status.keyword",
        "size": 100
      },
      "aggs": {
        "Sum": {
          "value_count": {
            "field": "status.keyword"
          }
        },
        "ExistsPostShipmentDate": {
          "filter": {
            "exists": {
              "field": "post_shipment_date"
            }
          }
        },
        "SumGetFullPacked": {
          "filter": {
            "term": {
              "soitem_picked_full": "1"
            }
          }
        },
        "GapTreLeadTime": {
          "filter": {
            "range": {
              "updated_at": {
                "gte": "now-2000d/d",
                "lte": "now"
              }
            }
          },
          "aggs": {
            "exsd_leadtime_minues_hours": {
              "filter": {
                "script": {
                  "script": {
                    "source": "\n                             Instant Currentdate = Instant.ofEpochMilli(new Date().getTime());\n                             ZonedDateTime mdt = doc['exsd'].length > 0 ?doc['exsd'].value : null;\n                             ZonedDateTime nowDT = ZonedDateTime.ofInstant(Currentdate, ZoneId.of('Z'));\n                             if(mdt != null){\n                                // 18 - 7\n                                if(mdt.getHour() == 11){\n                                  mdt = mdt.plusHours(-1);\n                                }else{\n                                  mdt = mdt.plusHours(-5);\n                                }\n                             }\n                             return mdt == null || nowDT.isAfter(mdt);\n                            ",
                    "lang": "painless"
                  }
                }
              }
            },
            "exsd_leadtime": {
              "filter": {
                "script": {
                  "script": {
                    "source": "\n                             Instant Currentdate = Instant.ofEpochMilli(new Date().getTime());\n                             ZonedDateTime mdt = doc['exsd'].length > 0 ?doc['exsd'].value : null;\n                             ZonedDateTime nowDT = ZonedDateTime.ofInstant(Currentdate, ZoneId.of('Z'));\n\n                             return mdt == null || nowDT.isAfter(mdt);\n                           ",
                    "lang": "painless"
                  }
                }
              }
            }
          }
        },
        "duddd": {
          "range": {
            "field": "",
            "ranges": [
              {
                "from": 50,
                "to": 100
              }
            ]
          }
        }
      }
    },
    "FacePacked": {
      "filter": {
        "term": {
          "status": "packed"
        }
      },
      "aggs": {
        "ExistsPostShipmentDate": {
          "filter": {
            "exists": {
              "field": "post_shipment_date"
            }
          }
        }
      }
    }
  }
}

### SEARCH INDEX
POST {{baseUrl}}/search/_index HTTP/1.1
content-type: application/json

[{
  "attribute": [
    {
      "attributeCode": "color_code",
      "attributeDisplayedValue": "AMAZON GREEN",
      "attributeName": "color_code",
      "attributeValue": "AMAZON GREEN",
      "isVariant": true
    },
    {
      "attributeCode": "color_name",
      "attributeDisplayedValue": "Xanh lá",
      "attributeName": "color_name",
      "attributeValue": "Xanh lá",
      "isVariant": true
    },
    {
      "attributeCode": "size",
      "attributeDisplayedValue": "M",
      "attributeName": "size",
      "attributeValue": "M",
      "isVariant": true
    }
  ],
  "brandCode": "1001",
  "brandName": "ECKO UNLTD",
  "categoryCode": "11009",
  "categoryId": 0,
  "categoryName": "POLO",
  "fullPrice": 1267000,
  "id": "6868002192408",
  "listedPrice": 1267000,
  "parentCode": "OF21-03151",
  "productCode": "6868002192408",
  "productImage": "/o/f/of21-03151_fw21_amazon_green_l-1_2.jpg",
  "productName": "ECKO UNLTD ÁO THUN CÓ CỔ TAY NGẮN NAM Xanh lá (AMAZON GREEN) M",
  "salesPrice": 1267000
}]