@baseUrl = http://localhost:3000/v0/item


### GET /id.{id}
GET {{baseUrl}}/id.41/ HTTP/1.1
content-type: application/json

### GET /{sku_code}
GET {{baseUrl}}/8025727438204 HTTP/1.1
content-type: application/json

### CREATE
POST {{baseUrl}}/ HTTP/1.1
content-type: application/json

{
    "code": "ecko-unltd-giay-sneakers-nam-is22-26511",
    "name": "Ecko Unltd giày sneakers nam IS22-26511",
    "variant_attributes": {
      "color": "red",
      "size": "L"
    },
    "master_sku": "",
    "primary_category_id": 4,
    "brand_id": 3,
    "categories_id": [18, 22],
    "created_by": "admin",
    "updated_by": "admin"
}

### UPDATE 
# Specify ID via path and only POST updated fields
POST {{baseUrl}}/id.41 HTTP/1.1
content-type: application/json

{ 
    "variant_attributes": {
      "color": "red",
      "size": "L"
    },    
    "updated_by": "admin"
}

### SEARCH
POST {{baseUrl}}/search HTTP/1.1
content-type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "brandCode": {
              "value": "1001"
            }
          }
        }
      ]
    }
  }
}